export type CatalogItem = {
  id: string;
  slug: string;
  type: "service" | "product";
  title: string;
  category: string;
  normalizedCategory?: string;
  subtitle: string;
  description: string;
  shortDescription?: string;
  fullDescription?: string;
  price: number;
  priceRub?: number | null;
  priceUsd?: number | null;
  priceLabel?: string | null;
  badge: string;
  availability?: string;
  availabilityStatus?: "IN_STOCK" | "ON_REQUEST" | "OUT_OF_STOCK" | "UNKNOWN";
  publicationStatus?: "DRAFT" | "PUBLISHED" | "ARCHIVED";
  icon: string;
  accent: "tarot" | "candle" | "amulet" | "game" | "rod" | "stone";
  details: string[];
  image?: string;
  gallery?: string[];
  tags?: string[];
  quantity?: number | null;
  needsReview?: boolean;
  sourceId?: string;
  sourcePlatform?: string;
  sourceUrl?: string;
};
